{if isset( $config.use_minified_js ) and $config.use_minified_js}
    <script type="text/javascript" src="{genUrl}/js/min.bundle-v18.js"></script>
{else}
    <script type="text/javascript" src="{genUrl}/js/100-jquery.js"></script>
    <script type="text/javascript" src="{genUrl}/js/120-jquery.validate.js"></script>
    <script type="text/javascript" src="{genUrl}/js/130-jquery.colorbox.js"></script>
    <script type="text/javascript" src="{genUrl}/js/150-jquery.datatables.js"></script>
    <script type="text/javascript" src="{genUrl}/js/151-jquery.datatables.ext.js"></script>
    <script type="text/javascript" src="{genUrl}/js/300-chosen.jquery.js"></script>
    <script type="text/javascript" src="{genUrl}/js/310-throbber.js"></script>
    <script type="text/javascript" src="{genUrl}/js/800-bootstrap.js"></script>
    <script type="text/javascript" src="{genUrl}/js/850-bootbox.js"></script>
    <script type="text/javascript" src="{genUrl}/js/900-vimbadmin.validate.js"></script>
    <script type="text/javascript" src="{genUrl}/js/910-vimbadmin.functions.js"></script>
    <script type="text/javascript" src="{genUrl}/js/990-vimbadmin.js"></script>
    <script type="text/javascript" src="{genUrl}/js/jquery-migrate-3.5.2.js"></script>
{/if}
