<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * DirectoryEntry
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends EntityRepository<\Entities\DirectoryEntry>
 */
class DirectoryEntry extends EntityRepository
{
}
