<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * Log
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends EntityRepository<\Entities\Log>
 */
class Log extends EntityRepository
{
	/**
     * Load logs for log list .
     *
     * @param \Entities\Admin|null $admin Admin for filtering mailboxes.
     * @param \Entities\Domain|null $domain Domain for filtering mailboxes.
     * @return array<int,array{id:mixed,action:mixed,data:mixed,timestamp:mixed,admin:mixed,domain:mixed}>
     */
    public function loadForLogList( $admin, $domain = null )
    {
        return $this->logListQuery( $admin, $domain )->getQuery()->getArrayResult();
    }

    private function logListQuery( ?\Entities\Admin $admin, ?\Entities\Domain $domain ): QueryBuilder
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select( 'l.id as id , l.action as action, l.data as data, l.timestamp as timestamp, a.username as admin, d.domain as domain' )
            ->from( '\\Entities\\Log', 'l' )
            ->leftJoin( 'l.Domain', 'd' )
            ->join( 'l.Admin', 'a' );

        if( $admin )
            $qb->join( 'd.Admins', 'd2a' )
                ->where( 'd2a = ?1' )
                ->setParameter( 1, $admin );

        if( $domain )
            $qb->andWhere( 'l.Domain = ?2' )
                ->setParameter( 2, $domain );

        return $qb;
    }

    /**
     * One page of the log list for DataTables server-side processing.
     *
     * The log table grows unbounded, so this never materialises the whole set:
     * it applies the global search, ORDER BY and LIMIT/OFFSET in SQL and returns
     * the page plus total / filtered counts. Search binds a parameter; the sort
     * field is whitelisted by the caller. `COUNT(DISTINCT l.id)` because the
     * non-system `d.Admins` join fans rows out.
     *
     * @param \Entities\Admin|null  $admin   null = system/super scope (all)
     * @param \Entities\Domain|null $domain
     * @return array{rows: array<int,array{id:mixed,action:mixed,data:mixed,timestamp:mixed,admin:mixed,domain:mixed}>, total: int, filtered: int}
     */
    public function pagedForLogList( $admin, $domain, string $search, string $sortField, string $sortDir, int $start, int $length )
    {
        // Unfiltered total stable per scope -> cache briefly (the log is large).
        $scopeKey = 'vimb_total_log_' . ( is_object( $admin ) ? $admin->getId() : 0 ) . '_' . ( $domain ? $domain->requiredId() : 0 );
        $total    = (int) $this->logCountQuery( $admin, $domain, '' )->getQuery()
            ->enableResultCache( 30, $scopeKey )->getSingleScalarResult();
        $filtered = $search === ''
            ? $total
            : (int) $this->logCountQuery( $admin, $domain, $search )->getQuery()->getSingleScalarResult();

        $rows = $this->pagedLogRowsQuery( $admin, $domain, $search, $sortField, $sortDir, $start, $length )
            ->getQuery()->getArrayResult();

        return [ 'rows' => $rows, 'total' => $total, 'filtered' => $filtered ];
    }

    private function scopedLogQuery( ?\Entities\Admin $admin, ?\Entities\Domain $domain ): QueryBuilder
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->from( '\\Entities\\Log', 'l' )
            ->leftJoin( 'l.Domain', 'd' )
            ->join( 'l.Admin', 'a' );

        if( $admin )
            $qb->join( 'd.Admins', 'd2a' )->andWhere( 'd2a = :admin' )->setParameter( 'admin', $admin );

        if( $domain )
            $qb->andWhere( 'l.Domain = :domain' )->setParameter( 'domain', $domain );

        return $qb;
    }

    private function applyLogSearch( QueryBuilder $qb, string $search ): QueryBuilder
    {
        if( $search !== '' )
            $qb->andWhere( '( l.action LIKE :s OR l.data LIKE :s OR a.username LIKE :s OR d.domain LIKE :s )' )
               ->setParameter( 's', '%' . addcslashes( $search, '%_\\' ) . '%' );
        return $qb;
    }

    private function logCountQuery( ?\Entities\Admin $admin, ?\Entities\Domain $domain, string $search ): QueryBuilder
    {
        return $this->applyLogSearch( $this->scopedLogQuery( $admin, $domain ), $search )
            ->select( 'COUNT(DISTINCT l.id)' );
    }

    private function pagedLogRowsQuery( ?\Entities\Admin $admin, ?\Entities\Domain $domain, string $search, string $sortField, string $sortDir, int $start, int $length ): QueryBuilder
    {
        $sortMap = [ 'action' => 'l.action', 'admin' => 'a.username', 'domain' => 'd.domain', 'timestamp' => 'l.timestamp' ];
        $orderBy = $sortMap[ $sortField ] ?? 'l.timestamp';

        return $this->applyLogSearch( $this->scopedLogQuery( $admin, $domain ), $search )
            ->select( 'l.id as id, l.action as action, l.data as data, l.timestamp as timestamp, a.username as admin, d.domain as domain' )
            ->orderBy( $orderBy, $sortDir === 'ASC' ? 'ASC' : 'DESC' )
            ->setFirstResult( max( 0, $start ) )
            ->setMaxResults( max( 1, $length ) );
    }
}
