{tmplinclude file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >

        {if $user->isSuper()}
        <div style="float: right; margin-top: -10px;">
            <div class="btn-toolbar">
            	<span class="btn-group">
        	        <a class="btn" id="asign_domain have-tooltip" href="{genUrl controller='admin' action='assign-domain' aid=$targetAdmin->getId()}" title="Assign Domain" >
            	        <i class="icon-plus"></i>
        	        </a>
            	</span>
        	</div>
    	</div>
    	{/if}

        <h1>Domains<small> for {$targetAdmin->getUsername()}</small></h1>
    </div>

    {OSS_Message}


<table id="list_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Domain</th>
            <th width="30"></th>
        </tr>
    </thead>
    <tbody>
    {foreach $targetAdmin->getDomains() as $domain}
        <tr id="domain_{$domain->getId()}">
            <td>{$domain->requiredDomainName()}{if !$domain->getActive()} (inactive){/if}</td>
            <td>
                <a class="btn btn-small have-tooltip-below" id="remove-domain-{$domain->getId()}" href="{genUrl controller='admin' action='remove-domain' aid=$targetAdmin->getId() did=$domain->getId()}" ref="{$domain->requiredDomainName()}" title="Remove">
                    <i class="icon-minus"></i>
                </a>
            </td>
        </tr>
    {/foreach}
    </tbody>
</table>
<br/>
<br/>

<div id="purge_dialog" class="modal fade" tabindex="-1" aria-hidden="true">

    <div class="modal-dialog modal-dialog-centered">

        <div class="modal-content">

            <div class="modal-header">
                <h3 class="modal-title">Are you sure?</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to remove <em id="purge_admin_name">{$targetAdmin->getUsername()}</em> from <em id="purge_domain_name"></em> ?
            </div>
            <div id="pdfooter" class="modal-footer">
                <form id="remove_domain_form" method="post" action="{genUrl controller='admin' action='remove-domain'}" style="display: inline;">
                    <input type="hidden" name="aid" value="{$targetAdmin->getId()}" />
                    <input type="hidden" name="did" value="" />
                    <input type="hidden" name="csrf" value="{$csrfToken|escape}" />
                    <button class="btn btn-danger" id="purge_dialog_delete" type="submit">Remove</button>
                </form>
                <button id="purge_dialog_cancel" class="btn">Cancel</button>
            </div>

        </div>

    </div>
</div>

<script type="text/javascript" nonce="{$cspNonce}">{tmplinclude file='admin/js/domains.js'}</script>
</div>
{tmplinclude file="footer.phtml"}
