{tmplinclude file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >
        <div style="float: right; margin-top: -10px;">
            <div class="btn-toolbar">
            	<span class="btn-group">
        	        <a class="btn have-tooltip-below" id="add_admin" title="Assign Administrator" href="{genUrl controller='domain' action='assign-admin' did=$domain->getId()}">
            	        <i class="icon-plus"></i>
        	        </a>
            	</span>
        	</div>

    	</div>

        <h1>Domain Administrators <small>for {$domain->requiredDomainName()}</small></h1>
    </div>

{OSS_Message}

<table id="list_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Username</th>
            <th width="30"></th>
        </tr>
    </thead>
    <tbody>
    {foreach $domain->getAdmins() as $admin}
        {if !$admin->isSuper()}
            <tr id="admin_{$admin->getId()}">
                <td>{$admin->getUsername()}{if !$admin->getActive()} <em>(inactive)</em>{/if}</td>
                <td>
                    <form method="post" action="{genUrl controller='domain' action='remove-admin'}" class="remove-admin-form" style="display: inline;">
                        <input type="hidden" name="aid" value="{$admin->getId()}" />
                        <input type="hidden" name="did" value="{$domain->getId()}" />
                        <input type="hidden" name="csrf" value="{$csrfToken|escape}" />
                        <button class="btn btn-small have-tooltip" ref="{$admin->getUsername()}" id="remove-admin-{$admin->getId()}" title="Remove" type="submit">
                            <i class="icon-minus"></i>
                        </button>
                    </form>
                </td>
            </tr>
        {/if}
    {/foreach}
    </tbody>
</table>
<br/>
<br/>
</div>

<div id="purge_dialog" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
        Are you sure you want to remove <em id="purge_admin_name"></em> ?
    </div>
    <div id="pdfooter" class="modal-footer">
        <a class="btn btn-danger" id="purge_dialog_delete" href="#">Remove</a>
        <button id="purge_dialog_cancel" class="btn">Cancel</button>
    </div>
</div>
<script type="text/javascript" nonce="{$cspNonce}">{tmplinclude file='domain/js/admins.js'}</script>
{tmplinclude file="footer.phtml"}
