{tmplinclude file="header.phtml" }

<div class="page-content" >

    <div class="page-header" >

        <div style="float: right; margin-top: -10px;">
            <div class="btn-toolbar">
            	<span class="btn-group">
            	    {if $ima}   
                        <a class="btn have-tooltip-below" id="ima" title="Hide Mailbox Aliases" href="{genUrl controller='mailbox' action='aliases' ima=0 mid=$mailbox->getId()}" >
                            <i class="icon-eye-close"></i>
                        </a>
                    {else}
                        <a class="btn have-tooltip-below" id="ima" title="Show Mailbox Aliases" href="{genUrl controller='mailbox' action='aliases' ima=1 mid=$mailbox->getId()}" >
                            <i class="icon-eye-close"></i>
                        </a>
                    {/if}
        	        <a class="btn have-tooltip-below" id="add_alias" href="{genUrl controller='alias' action='add' mid=$mailbox->getId()}" title="Add Alias" >
            	        <i class="icon-plus"></i>
        	        </a>
            	</span>
        	</div>
    	</div>
        <h1>Aliases <small>for {$mailbox->requiredUsername()}</small></h1>

    </div>
    {OSS_Message}


    <table id="list_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Address</th>
                <th>Goto</th>
                <th width="30"></th>
            </tr>
        </thead>
        <tbody>
        {foreach $aliases as $alias}
            <tr id="alias_{$alias->getId()}">
                <td>{$alias->getAddress()}</td>
                <td >
                    <div id="alias-goto-{$alias->getId()}" {if $alias->getGoto()|strlen > 50}class="have-tooltip" title="{$alias->getGoto()|regex_replace:"/[,]/":", "}"{/if}>
                        {$alias->getGoto()|shorten:50}
                    </div>
                </td>
                <td>
                    <div class="btn-group">
                        <form method="post" action="{genUrl controller='mailbox' action='delete-alias'}" class="delete-alias-form" style="display: inline;">
                            <input type="hidden" name="mid" value="{$mailbox->getId()}" />
                            <input type="hidden" name="alid" value="{$alias->getId()}" />
                            <input type="hidden" name="csrf" value="{$csrfToken|escape}" />
                            <button class="btn btn-sm have-tooltip" ref="{$alias->getAddress()}" id="delete-alias-{$alias->getId()}" title="Remove" type="submit">
                                <i class="icon-trash"></i>
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        {/foreach}
        </tbody>
    </table>
    <br/>
    <br/>

    <script type="text/javascript" nonce="{$cspNonce}">{tmplinclude file='mailbox/js/aliases.js'}</script>

    <div id="purge_dialog" class="modal fade" tabindex="-1" aria-hidden="true">

        <div class="modal-dialog modal-dialog-centered">

            <div class="modal-content">

            <div class="modal-header">
                <h3 class="modal-title">Are you sure?</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to remove
                <em id="purge_alias_name"></em> from this entry?
            </div>
            <div id="pdfooter" class="modal-footer">
                <a class="btn btn-danger" id="purge_dialog_delete" href="#">Delete</a>
                <button id="purge_dialog_cancel" class="btn">Cancel</button>
            </div>

            </div>

        </div>
</div>


</div>
{tmplinclude file="footer.phtml"}
